package game;

import javax.swing.*;
import java.awt.*;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

/**
 * Created by st on 17/08/14.
 */
public class GameGui {

    public JFrame frame = new JFrame("Battleships...");

    public JPanel panel1 = new JPanel();
    public JLabel LabelEnterCoordsX = new JLabel();
    public JLabel LabelEnterCoordsY = new JLabel();
    public JTextField tFieldEnterCoordsX = new JTextField();
    public JTextField tFieldEnterCoordsY = new JTextField();
    public JLabel LabelUserMessages = new JLabel();
    public JLabel LabelResults = new JLabel();
    public JButton ButtonFire = new JButton();


    public void createUIComponents() {
        // TODO: place custom component creation code here


        frame.setContentPane(panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

    }

    public void initGui() {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.jgoodies.looks.plastic.Plastic3DLookAndFeel");
                        createUIComponents();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    public static String userMessage(char selector) {

        /*
        Message types \ prefixes to String name:
            - m --    message
            - w --    warning
            - r --    results
            - i --    instructions
            - t --    title
         */


        // case 0
        String mWelcome = new String("A pretty simple game, choose coordinates x and y, where the values are between 1" +
                " and 25 inclusive,with a comma ',' in between, for example: 23,2");

        // case 1
        String iQuit = new String("Enter 'q' to quit the game.");

        // case 2
        String iEnterCoords = new String("Enter coordinates as 'x,y'");

        // case 3
        String rMissed = "Missed...";


        String message = new String();

        switch (selector) {
            case '0':
                message = mWelcome;
                break;
            case '1':
                message = iQuit;
                break;
            case '2':
                message = iEnterCoords;
                break;
            case '3':
                message = rMissed;
                break;
        }

        return message;
    }

    public void setData(GameGui data) {
    }

    public void getData(GameGui data) {
    }

    public boolean isModified(GameGui data) {
        return false;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.setMinimumSize(new Dimension(400, 200));
        panel1.setName("Game");
        panel1.setPreferredSize(new Dimension(400, 200));
        LabelEnterCoordsX = new JLabel();
        LabelEnterCoordsX.setText("Enter X Coordinates");
        CellConstraints cc = new CellConstraints();
        panel1.add(LabelEnterCoordsX, cc.xy(1, 3, CellConstraints.LEFT, CellConstraints.DEFAULT));
        LabelEnterCoordsY = new JLabel();
        LabelEnterCoordsY.setText("Enter Y Coordinates");
        panel1.add(LabelEnterCoordsY, cc.xy(1, 5, CellConstraints.LEFT, CellConstraints.DEFAULT));
        tFieldEnterCoordsX = new JTextField();
        panel1.add(tFieldEnterCoordsX, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        LabelUserMessages = new JLabel();
        LabelUserMessages.setText("User Message:");
        panel1.add(LabelUserMessages, cc.xywh(1, 1, 4, 2));
        ButtonFire = new JButton();
        ButtonFire.setText("Fire!");
        panel1.add(ButtonFire, cc.xy(1, 7));
        tFieldEnterCoordsY = new JTextField();
        panel1.add(tFieldEnterCoordsY, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        LabelResults = new JLabel();
        LabelResults.setText("");
        panel1.add(LabelResults, cc.xy(3, 7));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
